
---
name: GetInfo
author: ImagicalGamer
version: "1.0"
api: [1.0.0, 2.0.0, 3.0.0]
main: ImagicalGamer\Status\Main
commands:
 status:
  description: Shows server status!
 info:
  description: Get a players info!
...
